server:
  port: 8081

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://postgres:5432/library
    username: 'admin'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672

security:
  jwt:
    secret: aGhoamtoamtndWdibSxCPE5CTkg8Z2hqZ2poZ3ZCR0ZHVk1CbW5ibW5iSkhHSHZibk08bnZIR0hW
    access: 1
    refresh: 30

openapi:
  service:
    title: book-service doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    path: /book-service/swagger-ui.html
  override-with-generic-response: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true